# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96ccc78cc606f72e59aa1b2a0fe57d33f7de41366037a02380ae13f78c056d4f1aba98c0e0ea569fbe9431f4ab76862a4dce6a5d41ec07bfd5d5bf75679c7ea1

test:
  secret_key_base: d4440982629f9f59d4fa13873eb585271758457260ea84f70820775f45bc8761176269ccbd889f006a5fc4e8fd1f8ed862649519d2a84c866f4790e0ddeea1f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
